### ISSUE TITLE
Remove the need to be a subtype of `MLJModelInterface.Model`

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaAI/MLJModelInterface.jl#10]
If I understand correctly, right now, if you have a type and you want it to implement the MLJ model interface, your type needs to be a subtype of `MLJModelInterface.Model` (either a direct subtype of `MLJModelInterface.Model`, or a subtype of one of `MLJModelInterface.Model`'s subtypes, etc.).

However, suppose my type is already a subtype of something else, such as `MyOwnAbstractType`. Now life is difficult. I have to use composition to make a "wrapper" type that wraps my original type, and then the "wrapper" type is a subtype of `MLJModelInterface.Model`. This is a real pain, especially if I am trying to implement multiple interfaces (MLJ, ScikitLearnBase, etc.) - I would need a separate wrapper type for each interface that I am implementing.

I think it should be sufficient for a type to implement the appropriate functions, such as `MLJModelInterface.fit`, `MLJModelInterface.predict`, etc.

Would it be possible to remove the requirement that a type needs to be a subtype of `MLJModelInterface.Model` in order to implement the MLJ model interface?

cc: @ablaom @tlienart @juliohm - feel free to ping other people that will be interested.

**Comment by tlienart** [comment]
Well there's a bunch of despatching that happens based on the type in particular Deterministic/Probabilistic, changing this would  be a major refactoring as far as I know... 

Possible ways around are to:

- have your abstract type subtype one of the model types
- have other types specific for the interface (e.g. what I did in MLJLinearModels)

**Comment by juliohm** [comment]
I fully agree with this. Despite the major refactoring of code involved, I think the whole MLJ ecosystem would improve. The main challenge nowadays is the fact that the language doesn't provide sugar syntax to assert traits directly at compile time, and so we need to rewrite things manually.

**Comment by tlienart** [comment]
Let’s imagine we went down that road, how would you encourage/enforce for instance that models are only containers for hyper parameters? Devs may want to have their own struct which contains the learned parameter, I’m not saying that’s what you’re doing but such devs would then want to allow this; my point is that inevitably there’s a point where we have to enforce some structure on our side and require people to implement some form of interface that complies with said structure, and inevitably there will be people who are not happy with this because it requires them to add some specific logic to support it. 

Anyway I think it’s an important point that you’re raising and there may be a way to help writing interfaces to reduce the kind of pains you’re describing (and suggestions to do so are very welcome) but a refactoring to ditch the type system altogether and fully go with traits is something that I don’t think we can justify before MLJ 2... in my opinion that energy is currently better allocated at trying to support users, model tuning, composition etc

**Comment by juliohm** [comment]
The view of models as containers of hyperparameters is great, and I follow it strictly when coding new models. I don't know, however, if it is a requirement since the `fit/predict` workflow still works no matter where the learned parameters are saved. Perhaps allowing general structure is a positive thing, but certainly users and devs could be informed in the documentation about the benefits of only storing hyperparameters. The main benefit as I see it now is the low-memory requirements and associated lightweight instances that can be passed around quickly.

I second the idea that a whole redesign in terms of traits requires a major version, and more time from people who are already too busy polishing the MLJ stack. Maybe this issue can be addressed in the future after we have a better understanding of the implications, and after the language provides more explicit support to traits.

**Comment by ablaom** [comment]
Closing, as too ambitious at present.
