### ISSUE TITLE
Model type hierarchy doesn't scale

### ISSUE THREAD

**Issue by juliohm** [JuliaAI/MLJModelInterface.jl#120]
We could be doing much better if instead of a type hierarchy we had a set of trait functions for `isprobabilistic` `issupervised` like I do in GeoStatsBase.jl Currently we have Unsupervised models that are Probabilistic like `GMMClusterer` and yet we can't place them in the type hierarchy.

Any plans to refactor this types into a set of trait functions in the long-term?

**Comment by juliohm** [comment]
Reference to trait-based approach: https://github.com/JuliaEarth/GeoStatsBase.jl/blob/d5a4bdc0ee676b1077a4fbff929cfc6e272e8088/src/learning/traits.jl#L18-L32

**Comment by ablaom** [comment]
@juliohm Thanks for these observations.

> Any plans to refactor this types into a set of trait functions in the long-term?

Not really, as this would be a huge refactor.

However, there is already a trait (shared by models and metrics) called `prediction_type` which can have value `:deterministic`, `:probabilistic`, `:interval` or `:unknown`.  (Do `info(model)` to get a list of all the traits of a model.)
Naturally, for `Probabilistic`, `Deterministic` and `Interval` subtypes of `Supervised`, there is the obvious fallback.  In principle the existence of this trait means we could do away with the with this subtyping, but this has not been considered because of the disruption.

**Comment by DilumAluthge** [comment]
See also https://github.com/JuliaAI/MLJModelInterface.jl/issues/10 for a previous discussion.
