### ISSUE TITLE
selectrows() doesn't work with AbstractDict

### ISSUE THREAD

**Issue by ven-k** [JuliaAI/MLJModelInterface.jl#77]
When `class_w` is passed to a machine during construction, it eventually throws an error on evaluation. (Holds true for any `fit...` function)

```
X, y = table(rand(100, 5)), coerce(rand([1,2,3], 100), Multiclass)
class_w = Dict(1=>1, 2=>2, 3=>3)
model  = @load DeterministicConstantClassifier
mach = machine(model, X, y, class_w)
evaluate!(mach, measure=multiclass_f1score)
```

On first pass, I believe its because `selectrow()` in `data_utils.jl` doesn't support `AbstractDict`s yet. 

I can work on it, if it's to be added.

**Comment by ablaom** [comment]
Ah yes, we have essentially been assuming all the `args` in `fit(model, verbosity, args...)` are objects to be subsampled, but in the class weights case this is not so. 

One solution would be to have a fallback for `selectrows` that just returns the object unsampled. But this might mean objects *not* meant to be sampled, but which appear to be iterable (any table, matrix or vector) would get sampled. So such objects would need to be passed to fit in some wrapped form to force the `selectrows` fallback to kick in. Since I can't actually think of a single use-case (*maybe* https://github.com/alan-turing-institute/MLJ.jl/issues/480), this may not be so bad. 

An alternative would be to pass objects not intended for sampling as keyword arguments (keyword arguments are currently forbidden). So, for example, if `w` is a per-sample weight, we do

    fit(model, verbosity, X, y, w)

but for class weight `class_w`, we do

    fit(model, verbosity, X, y; class_weight=class_w)

I think it would be complicated to adapt the machine interface and the composition interface to this change; I'm not enthusiastic about the prospect. The user would also need to use keywords in the machine constructor, and is would probably appear weird to users to have a keyword for class weights and no keyword for sample weights. 

So my vote is for the first option. 

Any other ideas?

Option 1 is a simple PR, so I'll make that now; but we can sit on that for a week or so.

**Comment by ablaom** [comment]
The new data front-end also provides the possibility of overriding any (most?) unexpected behaviour with option 1. So let's go for that.
