### ISSUE TITLE
Handling of accelerator / device in model interface

### ISSUE THREAD

**Issue by jeremiedb** [JuliaAI/MLJModelInterface.jl#93]
Is there a preferred way to instruct MLJ to request an algorithm to be run on CPU vs GPU? 

I noticed the section pertaining to `acceleration` in https://alan-turing-institute.github.io/MLJ.jl/dev/, however I'm not sure if such is compatible in cases where a model cannot directly sent to the gpu such as with Flux model `m = m |> gpu`. 

More specifically, as I'm reworking the GPU acceleration of EvoTrees. Current scenario is to simply instruct device usage though the model parameters. Ie, add  `device = "cpu" | "gpu"` to other params such as `depth`, which would return an EvoTreeRegressor{:CPU | :GPU} that could be dispatch to appropriate fitting routines. As such, there wouldn't be any usage of the `accelerator` component of MLJ. Does it appears like a sound approach?

**Comment by ablaom** [comment]
@jeremiedb Very sorry, I seemed to have missed this one!

Let me say what is done in MLJFlux, and you tell me if this answers your question.

In MLJFlux each model (in the sense of MLJ, not in the sense of Flux) has a hyperparameter called `acceleration` (not `accelerator`). If this is set to `CUDALibs()` (from ComputationalResources.jl) then data and the Flux model (chain) is moved onto the GPU for training. The Flux model (chain), being the learned parameters) is moved back to the CPU after training so that model serialisation / deserialisation works without issues. 

If `acceleration=CPU1()` then training is on the CPU as normal. 

The word "device" is not really ideal, as an option such as `CPUThreads()` is not really a "device", right? For consistency with the MLJ api, I suggest you use `acceleration` in your MLJ-facing model struct, if possible. We should have (but did not) document this as a requirement of the API.

**Comment by ablaom** [comment]
Closing in favour of #104. Feel free to continue discussion below.;
